const express=require("express")
const cors=require("cors")
const dotenv=require("dotenv")
dotenv.config()
require("./db.js")
const app=express()
app.use(cors())
app.use(express.json())
app.use("/uploads",express.static("uploads/"))
const adminctrl=require("./Controllers/admincontroller.js")
app.use("/admin",adminctrl)
const userctrl=require("./Controllers/usercontroller.js")
app.use("/user",userctrl)
const libraryctrl=require("./Controllers/librarycontroller.js")
app.use("/library",libraryctrl)
const bookctrl=require("./Controllers/bookcontroller.js")
app.use("/book",bookctrl)
const requestctrl=require("./Controllers/requestcontroller.js")
app.use("/request",requestctrl)
app.listen(8080,()=>{
     console.log("Server running at port no:8080")
})
